name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set gem version
        run: echo "$(gem build suiteview.gemspec -v | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build . -t suiteview:$GITHUB_OUTPUT
