name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set gem version
        run: echo "::set-output name=gem_version::$(gem build suiteview.gemspec -v | cut -d ' ' -f 2)"
        id: gem_version

      - name: Build Docker image
        run: docker build . -t suiteview:${{ steps.gem_version.outputs.gem_version }}
